/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceCategory = IDL.Variant({
  'plumber' : IDL.Null,
  'chef' : IDL.Null,
  'pestControl' : IDL.Null,
  'carpenter' : IDL.Null,
});
export const Time = IDL.Int;
export const ProfessionalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'suspended' : IDL.Null,
});
export const AvailabilityStatus = IDL.Variant({
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const ProfessionalProfile = IDL.Record({
  'bio' : IDL.Text,
  'status' : ProfessionalStatus,
  'name' : IDL.Text,
  'workingRadius' : IDL.Nat,
  'availability' : AvailabilityStatus,
  'aggregateRating' : IDL.Opt(IDL.Float64),
  'category' : ServiceCategory,
  'phone' : IDL.Text,
  'subSkills' : IDL.Vec(IDL.Text),
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'onTheWay' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'customer' : IDL.Principal,
  'date' : Time,
  'cancellationFee' : IDL.Bool,
  'subService' : IDL.Text,
  'professional' : IDL.Principal,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'category' : ServiceCategory,
  'amount' : IDL.Nat,
  'timeSlot' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Variant({ 'customer' : IDL.Null, 'professional' : IDL.Null }),
  'phone' : IDL.Text,
});
export const CustomerProfile = IDL.Record({
  'name' : IDL.Text,
  'addresses' : IDL.Vec(IDL.Text),
  'phone' : IDL.Text,
});
export const ProfessionalEarnings = IDL.Record({
  'weeklyEarnings' : IDL.Nat,
  'monthlyEarnings' : IDL.Nat,
  'dailyEarnings' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
});
export const Review = IDL.Record({
  'bookingId' : IDL.Nat,
  'customer' : IDL.Principal,
  'comment' : IDL.Text,
  'professional' : IDL.Principal,
  'timestamp' : Time,
  'rating' : IDL.Nat8,
});
export const Service = IDL.Record({
  'basePriceEstimate' : IDL.Nat,
  'subService' : IDL.Text,
  'category' : ServiceCategory,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Principal,
        ServiceCategory,
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllProfessionals' : IDL.Func(
      [],
      [IDL.Vec(ProfessionalProfile)],
      ['query'],
    ),
  'getAvailableProfessionalsByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(ProfessionalProfile)],
      ['query'],
    ),
  'getBookingsByCustomer' : IDL.Func(
      [IDL.Principal, BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByProfessional' : IDL.Func(
      [IDL.Principal, BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CustomerProfile)],
      ['query'],
    ),
  'getProfessionalEarnings' : IDL.Func(
      [IDL.Principal],
      [ProfessionalEarnings],
      ['query'],
    ),
  'getProfessionalProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ProfessionalProfile)],
      ['query'],
    ),
  'getReviewsByProfessional' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'getServiceCatalog' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'registerProfessional' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ServiceCategory,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitReview' : IDL.Func([IDL.Nat, IDL.Nat8, IDL.Text], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateCustomerProfile' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateProfessionalAvailability' : IDL.Func([AvailabilityStatus], [], []),
  'updateProfessionalStatus' : IDL.Func(
      [IDL.Principal, ProfessionalStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceCategory = IDL.Variant({
    'plumber' : IDL.Null,
    'chef' : IDL.Null,
    'pestControl' : IDL.Null,
    'carpenter' : IDL.Null,
  });
  const Time = IDL.Int;
  const ProfessionalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const AvailabilityStatus = IDL.Variant({
    'offline' : IDL.Null,
    'online' : IDL.Null,
  });
  const ProfessionalProfile = IDL.Record({
    'bio' : IDL.Text,
    'status' : ProfessionalStatus,
    'name' : IDL.Text,
    'workingRadius' : IDL.Nat,
    'availability' : AvailabilityStatus,
    'aggregateRating' : IDL.Opt(IDL.Float64),
    'category' : ServiceCategory,
    'phone' : IDL.Text,
    'subSkills' : IDL.Vec(IDL.Text),
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'onTheWay' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'customer' : IDL.Principal,
    'date' : Time,
    'cancellationFee' : IDL.Bool,
    'subService' : IDL.Text,
    'professional' : IDL.Principal,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'category' : ServiceCategory,
    'amount' : IDL.Nat,
    'timeSlot' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Variant({ 'customer' : IDL.Null, 'professional' : IDL.Null }),
    'phone' : IDL.Text,
  });
  const CustomerProfile = IDL.Record({
    'name' : IDL.Text,
    'addresses' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
  });
  const ProfessionalEarnings = IDL.Record({
    'weeklyEarnings' : IDL.Nat,
    'monthlyEarnings' : IDL.Nat,
    'dailyEarnings' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
  });
  const Review = IDL.Record({
    'bookingId' : IDL.Nat,
    'customer' : IDL.Principal,
    'comment' : IDL.Text,
    'professional' : IDL.Principal,
    'timestamp' : Time,
    'rating' : IDL.Nat8,
  });
  const Service = IDL.Record({
    'basePriceEstimate' : IDL.Nat,
    'subService' : IDL.Text,
    'category' : ServiceCategory,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Principal,
          ServiceCategory,
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllProfessionals' : IDL.Func(
        [],
        [IDL.Vec(ProfessionalProfile)],
        ['query'],
      ),
    'getAvailableProfessionalsByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(ProfessionalProfile)],
        ['query'],
      ),
    'getBookingsByCustomer' : IDL.Func(
        [IDL.Principal, BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByProfessional' : IDL.Func(
        [IDL.Principal, BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getProfessionalEarnings' : IDL.Func(
        [IDL.Principal],
        [ProfessionalEarnings],
        ['query'],
      ),
    'getProfessionalProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ProfessionalProfile)],
        ['query'],
      ),
    'getReviewsByProfessional' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getServiceCatalog' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'registerProfessional' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ServiceCategory,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitReview' : IDL.Func([IDL.Nat, IDL.Nat8, IDL.Text], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateCustomerProfile' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateProfessionalAvailability' : IDL.Func([AvailabilityStatus], [], []),
    'updateProfessionalStatus' : IDL.Func(
        [IDL.Principal, ProfessionalStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };