/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AvailabilityStatus = { 'offline' : null } |
  { 'online' : null };
export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'customer' : Principal,
  'date' : Time,
  'cancellationFee' : boolean,
  'subService' : string,
  'professional' : Principal,
  'address' : string,
  'notes' : string,
  'category' : ServiceCategory,
  'amount' : bigint,
  'timeSlot' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'onTheWay' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export interface CustomerProfile {
  'name' : string,
  'addresses' : Array<string>,
  'phone' : string,
}
export interface ProfessionalEarnings {
  'weeklyEarnings' : bigint,
  'monthlyEarnings' : bigint,
  'dailyEarnings' : bigint,
  'totalEarnings' : bigint,
}
export interface ProfessionalProfile {
  'bio' : string,
  'status' : ProfessionalStatus,
  'name' : string,
  'workingRadius' : bigint,
  'availability' : AvailabilityStatus,
  'aggregateRating' : [] | [number],
  'category' : ServiceCategory,
  'phone' : string,
  'subSkills' : Array<string>,
}
export type ProfessionalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'suspended' : null };
export interface Review {
  'bookingId' : bigint,
  'customer' : Principal,
  'comment' : string,
  'professional' : Principal,
  'timestamp' : Time,
  'rating' : number,
}
export interface Service {
  'basePriceEstimate' : bigint,
  'subService' : string,
  'category' : ServiceCategory,
}
export type ServiceCategory = { 'plumber' : null } |
  { 'chef' : null } |
  { 'pestControl' : null } |
  { 'carpenter' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : { 'customer' : null } |
    { 'professional' : null },
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<
    [Principal, ServiceCategory, string, Time, string, string, string, bigint],
    bigint
  >,
  'getAllProfessionals' : ActorMethod<[], Array<ProfessionalProfile>>,
  'getAvailableProfessionalsByCategory' : ActorMethod<
    [ServiceCategory],
    Array<ProfessionalProfile>
  >,
  'getBookingsByCustomer' : ActorMethod<
    [Principal, BookingStatus],
    Array<Booking>
  >,
  'getBookingsByProfessional' : ActorMethod<
    [Principal, BookingStatus],
    Array<Booking>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerProfile' : ActorMethod<[Principal], [] | [CustomerProfile]>,
  'getProfessionalEarnings' : ActorMethod<[Principal], ProfessionalEarnings>,
  'getProfessionalProfile' : ActorMethod<
    [Principal],
    [] | [ProfessionalProfile]
  >,
  'getReviewsByProfessional' : ActorMethod<[Principal], Array<Review>>,
  'getServiceCatalog' : ActorMethod<[], Array<Service>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCustomer' : ActorMethod<[string, string, Array<string>], undefined>,
  'registerProfessional' : ActorMethod<
    [string, string, ServiceCategory, Array<string>, string, bigint],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitReview' : ActorMethod<[bigint, number, string], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateCustomerProfile' : ActorMethod<[Array<string>], undefined>,
  'updateProfessionalAvailability' : ActorMethod<
    [AvailabilityStatus],
    undefined
  >,
  'updateProfessionalStatus' : ActorMethod<
    [Principal, ProfessionalStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];