/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    customer: Principal;
    date: Time;
    cancellationFee: boolean;
    subService: string;
    professional: Principal;
    address: string;
    notes: string;
    category: ServiceCategory;
    amount: bigint;
    timeSlot: string;
}
export type Time = bigint;
export interface Service {
    basePriceEstimate: bigint;
    subService: string;
    category: ServiceCategory;
}
export interface ProfessionalProfile {
    bio: string;
    status: ProfessionalStatus;
    name: string;
    workingRadius: bigint;
    availability: AvailabilityStatus;
    aggregateRating?: number;
    category: ServiceCategory;
    phone: string;
    subSkills: Array<string>;
}
export interface ProfessionalEarnings {
    weeklyEarnings: bigint;
    monthlyEarnings: bigint;
    dailyEarnings: bigint;
    totalEarnings: bigint;
}
export interface CustomerProfile {
    name: string;
    addresses: Array<string>;
    phone: string;
}
export interface Review {
    bookingId: bigint;
    customer: Principal;
    comment: string;
    professional: Principal;
    timestamp: Time;
    rating: number;
}
export interface UserProfile {
    name: string;
    role: Variant_customer_professional;
    phone: string;
}
export enum AvailabilityStatus {
    offline = "offline",
    online = "online"
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    onTheWay = "onTheWay",
    accepted = "accepted",
    inProgress = "inProgress"
}
export enum ProfessionalStatus {
    pending = "pending",
    approved = "approved",
    suspended = "suspended"
}
export enum ServiceCategory {
    plumber = "plumber",
    chef = "chef",
    pestControl = "pestControl",
    carpenter = "carpenter"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_customer_professional {
    customer = "customer",
    professional = "professional"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelBooking(bookingId: bigint): Promise<void>;
    createBooking(professional: Principal, category: ServiceCategory, subService: string, date: Time, timeSlot: string, address: string, notes: string, amount: bigint): Promise<bigint>;
    getAllProfessionals(): Promise<Array<ProfessionalProfile>>;
    getAvailableProfessionalsByCategory(category: ServiceCategory): Promise<Array<ProfessionalProfile>>;
    getBookingsByCustomer(customer: Principal, status: BookingStatus): Promise<Array<Booking>>;
    getBookingsByProfessional(professional: Principal, status: BookingStatus): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerProfile(user: Principal): Promise<CustomerProfile | null>;
    getProfessionalEarnings(professional: Principal): Promise<ProfessionalEarnings>;
    getProfessionalProfile(user: Principal): Promise<ProfessionalProfile | null>;
    getReviewsByProfessional(professional: Principal): Promise<Array<Review>>;
    getServiceCatalog(): Promise<Array<Service>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerCustomer(name: string, phone: string, addresses: Array<string>): Promise<void>;
    registerProfessional(name: string, phone: string, category: ServiceCategory, subSkills: Array<string>, bio: string, workingRadius: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitReview(bookingId: bigint, rating: number, comment: string): Promise<void>;
    updateBookingStatus(bookingId: bigint, status: BookingStatus): Promise<void>;
    updateCustomerProfile(addresses: Array<string>): Promise<void>;
    updateProfessionalAvailability(availability: AvailabilityStatus): Promise<void>;
    updateProfessionalStatus(professional: Principal, status: ProfessionalStatus): Promise<void>;
}
import type { AvailabilityStatus as _AvailabilityStatus, Booking as _Booking, BookingStatus as _BookingStatus, CustomerProfile as _CustomerProfile, ProfessionalProfile as _ProfessionalProfile, ProfessionalStatus as _ProfessionalStatus, Service as _Service, ServiceCategory as _ServiceCategory, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async createBooking(arg0: Principal, arg1: ServiceCategory, arg2: string, arg3: Time, arg4: string, arg5: string, arg6: string, arg7: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async getAllProfessionals(): Promise<Array<ProfessionalProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfessionals();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfessionals();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableProfessionalsByCategory(arg0: ServiceCategory): Promise<Array<ProfessionalProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableProfessionalsByCategory(to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableProfessionalsByCategory(to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByCustomer(arg0: Principal, arg1: BookingStatus): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByCustomer(arg0, to_candid_BookingStatus_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByCustomer(arg0, to_candid_BookingStatus_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByProfessional(arg0: Principal, arg1: BookingStatus): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByProfessional(arg0, to_candid_BookingStatus_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByProfessional(arg0, to_candid_BookingStatus_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerProfile(arg0: Principal): Promise<CustomerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfessionalEarnings(arg0: Principal): Promise<ProfessionalEarnings> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfessionalEarnings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfessionalEarnings(arg0);
            return result;
        }
    }
    async getProfessionalProfile(arg0: Principal): Promise<ProfessionalProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfessionalProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfessionalProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsByProfessional(arg0: Principal): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByProfessional(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByProfessional(arg0);
            return result;
        }
    }
    async getServiceCatalog(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceCatalog();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceCatalog();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerCustomer(arg0: string, arg1: string, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCustomer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCustomer(arg0, arg1, arg2);
            return result;
        }
    }
    async registerProfessional(arg0: string, arg1: string, arg2: ServiceCategory, arg3: Array<string>, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfessional(arg0, arg1, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfessional(arg0, arg1, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitReview(arg0: bigint, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2);
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCustomerProfile(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomerProfile(arg0);
            return result;
        }
    }
    async updateProfessionalAvailability(arg0: AvailabilityStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfessionalAvailability(to_candid_AvailabilityStatus_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfessionalAvailability(to_candid_AvailabilityStatus_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProfessionalStatus(arg0: Principal, arg1: ProfessionalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfessionalStatus(arg0, to_candid_ProfessionalStatus_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfessionalStatus(arg0, to_candid_ProfessionalStatus_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AvailabilityStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvailabilityStatus): AvailabilityStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ProfessionalProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfessionalProfile): ProfessionalProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ProfessionalStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfessionalStatus): ProfessionalStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerProfile]): CustomerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfessionalProfile]): ProfessionalProfile | null {
    return value.length === 0 ? null : from_candid_ProfessionalProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    customer: Principal;
    date: _Time;
    cancellationFee: boolean;
    subService: string;
    professional: Principal;
    address: string;
    notes: string;
    category: _ServiceCategory;
    amount: bigint;
    timeSlot: string;
}): {
    id: bigint;
    status: BookingStatus;
    customer: Principal;
    date: Time;
    cancellationFee: boolean;
    subService: string;
    professional: Principal;
    address: string;
    notes: string;
    category: ServiceCategory;
    amount: bigint;
    timeSlot: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n20(_uploadFile, _downloadFile, value.status),
        customer: value.customer,
        date: value.date,
        cancellationFee: value.cancellationFee,
        subService: value.subService,
        professional: value.professional,
        address: value.address,
        notes: value.notes,
        category: from_candid_ServiceCategory_n13(_uploadFile, _downloadFile, value.category),
        amount: value.amount,
        timeSlot: value.timeSlot
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: {
        customer: null;
    } | {
        professional: null;
    };
    phone: string;
}): {
    name: string;
    role: Variant_customer_professional;
    phone: string;
} {
    return {
        name: value.name,
        role: from_candid_variant_n25(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    basePriceEstimate: bigint;
    subService: string;
    category: _ServiceCategory;
}): {
    basePriceEstimate: bigint;
    subService: string;
    category: ServiceCategory;
} {
    return {
        basePriceEstimate: value.basePriceEstimate,
        subService: value.subService,
        category: from_candid_ServiceCategory_n13(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    status: _ProfessionalStatus;
    name: string;
    workingRadius: bigint;
    availability: _AvailabilityStatus;
    aggregateRating: [] | [number];
    category: _ServiceCategory;
    phone: string;
    subSkills: Array<string>;
}): {
    bio: string;
    status: ProfessionalStatus;
    name: string;
    workingRadius: bigint;
    availability: AvailabilityStatus;
    aggregateRating?: number;
    category: ServiceCategory;
    phone: string;
    subSkills: Array<string>;
} {
    return {
        bio: value.bio,
        status: from_candid_ProfessionalStatus_n8(_uploadFile, _downloadFile, value.status),
        name: value.name,
        workingRadius: value.workingRadius,
        availability: from_candid_AvailabilityStatus_n10(_uploadFile, _downloadFile, value.availability),
        aggregateRating: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.aggregateRating)),
        category: from_candid_ServiceCategory_n13(_uploadFile, _downloadFile, value.category),
        phone: value.phone,
        subSkills: value.subSkills
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offline: null;
} | {
    online: null;
}): AvailabilityStatus {
    return "offline" in value ? AvailabilityStatus.offline : "online" in value ? AvailabilityStatus.online : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    plumber: null;
} | {
    chef: null;
} | {
    pestControl: null;
} | {
    carpenter: null;
}): ServiceCategory {
    return "plumber" in value ? ServiceCategory.plumber : "chef" in value ? ServiceCategory.chef : "pestControl" in value ? ServiceCategory.pestControl : "carpenter" in value ? ServiceCategory.carpenter : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    onTheWay: null;
} | {
    accepted: null;
} | {
    inProgress: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "onTheWay" in value ? BookingStatus.onTheWay : "accepted" in value ? BookingStatus.accepted : "inProgress" in value ? BookingStatus.inProgress : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    professional: null;
}): Variant_customer_professional {
    return "customer" in value ? Variant_customer_professional.customer : "professional" in value ? Variant_customer_professional.professional : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    suspended: null;
}): ProfessionalStatus {
    return "pending" in value ? ProfessionalStatus.pending : "approved" in value ? ProfessionalStatus.approved : "suspended" in value ? ProfessionalStatus.suspended : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProfessionalProfile>): Array<ProfessionalProfile> {
    return value.map((x)=>from_candid_ProfessionalProfile_n6(_uploadFile, _downloadFile, x));
}
function to_candid_AvailabilityStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityStatus): _AvailabilityStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_ProfessionalStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfessionalStatus): _ProfessionalStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Variant_customer_professional;
    phone: string;
}): {
    name: string;
    role: {
        customer: null;
    } | {
        professional: null;
    };
    phone: string;
} {
    return {
        name: value.name,
        role: to_candid_variant_n35(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    onTheWay: null;
} | {
    accepted: null;
} | {
    inProgress: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.onTheWay ? {
        onTheWay: null
    } : value == BookingStatus.accepted ? {
        accepted: null
    } : value == BookingStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_customer_professional): {
    customer: null;
} | {
    professional: null;
} {
    return value == Variant_customer_professional.customer ? {
        customer: null
    } : value == Variant_customer_professional.professional ? {
        professional: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityStatus): {
    offline: null;
} | {
    online: null;
} {
    return value == AvailabilityStatus.offline ? {
        offline: null
    } : value == AvailabilityStatus.online ? {
        online: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfessionalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    suspended: null;
} {
    return value == ProfessionalStatus.pending ? {
        pending: null
    } : value == ProfessionalStatus.approved ? {
        approved: null
    } : value == ProfessionalStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    plumber: null;
} | {
    chef: null;
} | {
    pestControl: null;
} | {
    carpenter: null;
} {
    return value == ServiceCategory.plumber ? {
        plumber: null
    } : value == ServiceCategory.chef ? {
        chef: null
    } : value == ServiceCategory.pestControl ? {
        pestControl: null
    } : value == ServiceCategory.carpenter ? {
        carpenter: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
